library(jsonlite)
library(rstan)
library(EnvStats)
stan_data <- jsonlite::fromJSON("Python/notebooks/test.json")
stan_data$SI <- dgammaAlt(c(1:130), mean=6.5, cv=0.62)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
m = stan_model(paste0('stan-models/',"county_mobility",'.stan'))
fit = sampling(m,data=stan_data,iter=40,warmup=20,chains=2)