countries:
  - Denmark
  - Italy
  - Germany
  - Spain
  - United_Kingdom
  - France
  - Norway
  - Belgium
  - Austria
  - Sweden
  - Switzerland

Italy:
  - CR 
  - LO 
  - PC 
  - BG 
  - BS 
  - PU 
  - AO 
  - RN 
  - PR 
  - LC 
  - PV 
  - RE
  - MN
  - AL 
  - TN 
  - MO 
  - MI 
  - VC 
  - AN 
  - PD 
  - BI 
  - TS 
  - BZ 
  - MB
  - BL
  - VB 
  - VR 
  - PE 
  - SO 
  - NO 
  - TV 
  - MC 
  - TO 
  - AT 
  - CO 
  - FC
  - VE
  - LU 
  - RA 
  - GE 
  - BO 
  - VI 
  - PT 
  - IM 
  - UD 
  - SV 
  - PG 
  - PI
  - CN
  - SI 
  - AR 
  - PN 
  - FI 
  - PO 
  - SS 
  - SP 
  - FE 
  - VA 
  - LI 
  - TE
  - FG
  - AV 
  - RO 
  - CH 
  - VT 
  - LT 
  - RM 
  - BR 
  - CT 
  - BA 
  - PZ 
  - ME
  - LE
  - NA 
  - RC 
  - FR 
  - SA 
  - BT 
  - CA 
  - CE 
  - AQ 
  - SR 
  - AG 
  - CS
  - PA
  - TA 
  - SU